// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuTb9HrqGeHyP7fnM2olMGXQkG6-CCGGE',
    appId: '1:838788857321:web:7cd7ec40d39229577adf78',
    messagingSenderId: '838788857321',
    projectId: 'flutter-login-app-3ce09',
    authDomain: 'flutter-login-app-3ce09.firebaseapp.com',
    storageBucket: 'flutter-login-app-3ce09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBooW-4dQdZevoWDvIXQT5jx4Y4qAj0qWw',
    appId: '1:838788857321:android:360c43dc1aab17907adf78',
    messagingSenderId: '838788857321',
    projectId: 'flutter-login-app-3ce09',
    storageBucket: 'flutter-login-app-3ce09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSaHCb5m-5DXi-5ka8BBJ5N7vGW3eMnA',
    appId: '1:838788857321:ios:64f7f8d84812d55b7adf78',
    messagingSenderId: '838788857321',
    projectId: 'flutter-login-app-3ce09',
    storageBucket: 'flutter-login-app-3ce09.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvSaHCb5m-5DXi-5ka8BBJ5N7vGW3eMnA',
    appId: '1:838788857321:ios:64f7f8d84812d55b7adf78',
    messagingSenderId: '838788857321',
    projectId: 'flutter-login-app-3ce09',
    storageBucket: 'flutter-login-app-3ce09.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuTb9HrqGeHyP7fnM2olMGXQkG6-CCGGE',
    appId: '1:838788857321:web:7c9d33a9cc8a2aca7adf78',
    messagingSenderId: '838788857321',
    projectId: 'flutter-login-app-3ce09',
    authDomain: 'flutter-login-app-3ce09.firebaseapp.com',
    storageBucket: 'flutter-login-app-3ce09.firebasestorage.app',
  );
}
